# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 733)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textInput = QtWidgets.QLineEdit(self.centralwidget)
        self.textInput.setGeometry(QtCore.QRect(90, 130, 541, 41))
        self.textInput.setStyleSheet("border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom: 1px solid #000;")
        self.textInput.setObjectName("textInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 110, 101, 16))
        self.label.setObjectName("label")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(630, 130, 101, 41))
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setStyleSheet("border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 5px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.searchBtn.setObjectName("searchBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 10, 341, 81))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.resultTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTable.setGeometry(QtCore.QRect(90, 190, 681, 471))
        self.resultTable.setStyleSheet("border: 0;")
        self.resultTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(5)
        self.resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "请输入歌名："))
        self.searchBtn.setText(_translate("MainWindow", "开始搜索"))
        self.label_2.setText(_translate("MainWindow", "云海 - 歌曲下载器"))
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "歌名"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "歌手"))
        item = self.resultTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "专辑"))
        item = self.resultTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "时常"))
